### PR TITLE
added hasher

### PR DESCRIPTION
**Pull request by konradowy**

### CODE REVIEW

**Comment by jakubvano** [comment]
Thanks for the PR! 👍 Build is failing because of Swinejct 2.7 no longer supporting Xcode 10.2 - we could fix this by bumping Xcode version in `travis.yml`

**Comment by lauramejiaarroyave** [comment]
I need this 👍

**Comment by lauramejiaarroyave** [comment]
Any updates to merge into a version?

**Comment by YamatoOtaka** [comment]
Can this be solved? https://github.com/Swinject/SwinjectStoryboard/pull/151

**Comment by yoichitgy** [comment]
Thank you for making the PR😃

It looks the change is covered by PR #135, so I'm going to close this issue.

**Pull request closed without merging**
