### PR TITLE
Swift 4.2 changes

### PR DESCRIPTION
**Pull request by tengyifei**

### CODE REVIEW

**Comment by NikSativa** [comment]
yes, it is just swift version coverage by preprocessor macros and support both versions at the same time

**Comment by bsarrazin** [comment]
It would be nice to do so I can stop modifying the source of SwinjectStoryboard in my demos 😂 
I'm too lazy to fork and make the modifications 😛

**Comment by oronbz** [comment]
Hey everyone!
Is there any reason this pull being delayed? It's holding us from upgrading to Xcode 10

**Comment by tengyifei** [comment]
@jakubvano

**Comment by abrahamduran** [comment]
I agree with @bsarrazin, I want to stop modifying the source of SwinjectStoryboard so often :p
Do you have any news about this?

**Comment by bsarrazin** [comment]
@NikSativa it's been 9 days since I've asked to make a new release.
What is the hold up? Anything we can help with?

**Comment by NikSativa** [comment]
@bsarrazin i was mentioned just as reviewer and i don't have permissions to make merge
@jakubvano @Lutzifer @tkohout @yoichitgy please help!

**Comment by JacobMao** [comment]
@tengyifei 

seems like I created a same PR
https://github.com/Swinject/SwinjectStoryboard/pull/110

but I also changed the test cases

**Comment by jakubvano** [comment]
Thanks for the PR @tengyifei! 👍   I'l try to release new version ASAP

**Comment by bsarrazin** [comment]
@tengyifei @jakubvano thank you! 🙏

**Pull request merged**
