### PR TITLE
Fix Error while building SwinjectStoryBoard with Xcode 12.5

### PR DESCRIPTION
**Pull request by tweetjay**
Hi, this will fix at least the build issue with Xcode 12.5 #154

### CODE REVIEW

**Review by SEQUOiA87 — APPROVED** [review]

**Review by alirp88 — APPROVED** [review]

**Comment by enzosterro** [comment]
Thanks for the quick fix and the PR that has been already approved. Is there a chance to get that merged in on this week?

**Comment by tweetjay** [comment]
It depends on the repository owner...

**Review by gbasile — APPROVED** [review]
Good work, any chance to get this merged soon?

**Comment by aeberbach** [comment]
This is pretty much the PR that I came to submit. Sure would be nice if it was merged.

**Comment by scottsymes** [comment]
Pull request #136 (Add Support for SwiftPM) also addresses this issue as the ObjectiveC code causing this issue has been refactored into Swift.

**Comment by yoichitgy** [comment]
Thank you for making the pull request😃 and sorry for taking too long time.

I checked the changes in my local environment and the build error was resolved. Thank you!😃

**Comment by tweetjay** [comment]
Thanks for merging! 😁

**Pull request merged**
