### PR TITLE
Migrate to prebuilt frameworks

### PR DESCRIPTION
**Pull request by jakubvano**
Version of Nimble had to be updated to support Xcode 8.3. While I was at it, I thought it might be beneficial to switch to using carthage as prebuild frameworks, analogously to [SwinjectAutoregistration #12](https://github.com/Swinject/SwinjectAutoregistration/issues/12).

### CODE REVIEW

**Comment by mpdifran** [comment]
Apple recommends building all Swift dependencies from source until the ABI is stabilized (i.e embedding the project itself instead of a pre-built framework). Is this going to cause any issues in regards to that, or can Carthage users still avoid using pre-built frameworks by specifying `--no-use-binaries` when updating?

**Comment by yoichitgy** [comment]
Thanks @mpdifran for clarifying what we are going to do.

The prebuilt framework of Swinject will be only used to build SwinjectStoryboard during development of SwinjectStoryboard. The prebuilt framework won't be embedded to an app. The app will include frameworks built with the following `Cartfile`.

```
github "Swinject/Swinject"
github "Swinject/SwinjectStoryboard"
```

**Comment by yoichitgy** [comment]
@jakubvano, I made a sample app to check this pull request. Cartfile is as below and I ran `carthage update --platform iOS` command:

```
github "Swinject/Swinject"  ~> 2.0.0
github "jakubvano/SwinjectStoryboard" "b41fc65b5451961a03f94ff451a784f270f8d97d"
```

but I got an error saying:

```
Dependency "SwinjectStoryboard" has no shared framework schemes for any of the platforms: iOS
```

An issue with the same error message is reported to Carthage project and already resolved at v0.20.1:
https://github.com/Carthage/Carthage/releases/tag/0.20.1

So the error I saw looked a different problem. I tried Carthage v0.19.1 and v0.18.1, and got the same error. Can you check the sample app and try building with Carthage?

My sample project is here: https://github.com/yoichitgy/SwinjectSbApp

**Comment by jakubvano** [comment]
Issue was caused by removing submodules for carthage dependencies - this caused missing `xcconfigs` (as it was only in Cartfile.private) when installing via carthage.

**Comment by yoichitgy** [comment]
I was thinking to copy and commit [xcconfigs](https://github.com/jspahrsummers/xcconfigs) files to the root directory of Swinject, SwinjectStoryboard and the other projects to solve [this issue](https://github.com/Swinject/Swinject/issues/130).

`xcconfigs` have no complicated logics, so we can commit the files to our own repo without submodules, and write the SHA1 of the `xcconfigs` commit version in our commit log.

If we have `xcconfigs` files committed to our repository, the problem we have here is also resolved😊

**Comment by mpdifran** [comment]
I was able to remove the `xcconfigs` submodule in my PR: #44 . Should we merge that PR first?

**Comment by jakubvano** [comment]
@yoichitgy sure, copying them to the repo is another solution. It is a bit [wet](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#DRY_vs_WET_solutions), but given that issue it looks like a way to go.

@mpdifran somehow i completely missed your PR, when starting this :/ However, your setup has the same issue as @yoichitgy pointed out above - installation via carthage doesn't work.

**Comment by mpdifran** [comment]
Hmm, I'm seeing no issue when I run `carthage update --no-use-binaries --no-build`. Or maybe I'm missing the issue? I can build the project afterwards with no warnings.

**Comment by jakubvano** [comment]
I can reproduce the issue by creating Cartfile
```
github "mpdifran/SwinjectStoryboard" "9f29a74eee4987a327ef3ad436bf785cf49ed403"
```
And running e.g. `carthage update --platform iOS`. Basically, `Carthage/Checkouts/xcconfigs` is missing thus schema configuration is incomplete and carthage is unable to properly identify schema for specific platform .

**Comment by yoichitgy** [comment]
I should have inform the @mpdifran's pull request #44 in this project. Sorry😢

Yeah, copying `xcconfigs` file to our repo is WET, but it's acceptable to copy only `xcconfigs`😓

**Comment by mpdifran** [comment]
Ah @jakubvano I thought you meant running `Carthage` for the `SwinjectStoryboard` project itself. Yeah looks like the best solution is the `WET` one.

**Comment by jakubvano** [comment]
I've created separate storyboards for tvOS tests - it seems that for quite some while our tvOS tests were not runnable: travis was executing tests for `Swinject-tvOS` schema instead of `SwinjectStoryboard-tvOS` (486669d)

**Comment by yoichitgy** [comment]
I noticed the problem too. When I tried to update [xcconfigs](https://github.com/jspahrsummers/xcconfigs), the storyboards for iOS didn't work on tvOS. That's why I sticked to the old version of xcconfigs.

It looks time to make separate storyboards for tvOS📺

**Comment by yoichitgy** [comment]
Thanks @mpdifran and @jakubvano for the changes😃 I merged this pull request along with #44😉

**Pull request merged**
